### ISSUE TITLE
Auctioneer log creates extra mappings in logsearch for cloudfoundry

### ISSUE THREAD

**Issue by saliceti** [cloudfoundry/auctioneer#5]
We use [logsearch](https://github.com/cloudfoundry-community/logsearch-boshrelease) and [logsearch-for-cloudfoundry](https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry) to aggregate our logs.
There is an issue with one log message emitted by the auctioneer at [this line](https://github.com/cloudfoundry/auctioneer/blob/af738c03227bcb3bf3df683801a1c14afcdccd2d/handlers/lrp_auction_handler.go#L60). For example:

```
<14>2016-12-09T12:45:59.071953+00:00 10.0.16.6 vcap.auctioneer [job=brain index=0]  {"timestamp":"1481287559.071580887","source":"auctioneer","message":"auctioneer.request.lrp-auction-handler.create.submitted","log_level":1,"data":{"lrps":{"df03138b-924d-417e-9743-abf81e577a70-7276869e-d03c-4ffd-9f83-18c366a390c3":[1]},"method":"POST","request":"/v1/lrps","session":"4900.1.1"}}
```

It logs `{"lrps": lrpGuids}` but `lrpGuids` is a map of GUID strings to []int. Therefore when it is parsed by logstash and sent to Elasticsearch, it is indexed and ES creates a mapping for it. Since the GUIDs are unique, it creates thousands of useless mappings that eventually end up breaking the kibana GUI.

We have a workaround for our cloud foudry deployment that consists in [flattening that specific data via logstash](https://github.com/alphagov/paas-cf/pull/663). But if we could find a way to fix this issue at origin that would be ideal. Maybe log an array of strings instead of a map?

**Comment by ematpl** [comment]
Thanks, @saliceti, that makes sense. We'll definitely remove the guids as JSON object keys. I don't have a strong opinion one way or the other about whether the data should be collapsed into an array of strings `["abc123:3,4,9",...]` or expanded further into an array of objects like `[{"guid":"abc123","indices":[3,4,9]},...]`: The former is more compact, but the latter is more machine-readable. So I'll let the pair that addresses this issue decide (or you, if you'd like to submit a PR!).

Thanks again,
Eric

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.
